<?php include("./template-header-connection.php"); ?>
<?php include("./template-header-html.php"); ?>

<div class="row">
  <h3>細目別採択状況</h3>
  <div class="col-md-6">
    <form method="GET" action="./saimokusearch.php">
      <div class="form-group">
        <label>細目</label>
        <input type="text" name="saimoku" class="form-control" id="shumokubetsu">
        <a href="#modalFade" id="modalTrigger" data-toggle="modal">細目を一覧から選択</a>
      </div>
      <button type="submit" class="btn btn-default">検索</button>
    </form>
    <hr>
    </div>

  <!-- modal dialog -->
  <div class="modal fade" id="modalFade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3>細目選択</h3>
        </div>
        <div class="modal-body row" id="saimoku">
          <div class="col-md-12">
            <input type="text" class="form-control" id="sentakuShumoku">
            <button id="set" data-dismiss="modal" class="btn btn-default">設定</button>
          </div>
          <div class="col-md-3">
            <h3>総合系</h3>
            <h4>情報学</h4>
              <h5>情報学基礎</h5>
              <ul>
              <li>情報学基礎理論</li>
<li>数理情報学</li>
<li>統計科学</li>
            </ul>
              <h5>計算基盤</h5>
              <ul>
              <li>計算機システム</li>
<li>ソフトウェア</li>
<li>情報ネットワーク</li>
<li>マルチメディア・データベース</li>
<li>高性能計算</li>
<li>情報セキュリティ</li>
            </ul>
              <h5>人間情報学</h5>
              <ul>
              <li>認知科学</li>
<li>知覚情報処理</li>
<li>ヒューマンインタフェース・インタラクション</li>
<li>知能情報学</li>
<li>ソフトコンピューティング</li>
<li>知能ロボティクス</li>
<li>感性情報学</li>
            </ul>
              <h5>情報学フロンティア</h5>
            <ul>
            <li>生命・健康・医療情報学</li>
<li>ウェブ情報学・サービス情報学</li>
<li>図書館情報学・人文社会情報学</li>
<li>学習支援システム</li>
<li>エンタテインメント・ゲーム情報学</li>
            </ul>
            <h4>環境学</h4>
            <h5>環境解析学</h5>
            <ul>
            <li>環境動態解析</li>
<li>放射線・化学物質影響科学</li>
<li>環境影響評価</li>
            </ul>
              <h5>環境保全学</h5>
              <ul>
              <li>環境技術・環境負荷低減</li>
<li>環境モデリング・保全修復技術</li>
<li>環境材料・リサイクル</li>
<li>環境リスク制御・評価</li>
            </ul>
              <h5>環境創成学</h5>
              <ul>
              <li>自然共生システム</li>
<li>持続可能システム</li>
<li>環境政策・環境社会システム</li>
              </ul>
              <h4>複合領域</h4>
              <h5>デザイン学</h5>
              <ul>
              <li>デザイン学</li>
            </ul>
              <h5>生活科学</h5>
              <ul>
              <li>家政・生活学一般</li>
<li>衣・住生活学</li>
<li>食生活学</li>
            </ul>
              <h5>科学教育・教育工学</h5>
              <ul>
              <li>科学教育</li>
<li>教育工学</li>
            </ul>
              <h5>科学社会学・科学技術史</h5>
              <ul>
              <li>科学社会学・科学技術史</li>
            </ul>
              <h5>文化財科学・博物館学</h5>
              <ul>
              <li>文化財科学・博物館学</li>
            </ul>
              <h5>地理学</h5>
              <ul>
              <li>地理学</li>
            </ul>
              <h5>社会・安全システム科学</h5>
              <ul>
              <li>社会システム工学・安全システム</li>
<li>自然災害科学・防災学</li>
            </ul>
              <h5>人間医工学</h5>
              <ul>
              <li>生体医工学・生体材料学</li>
<li>医用システム</li>
<li>医療技術評価学</li>
<li>リハビリテーション科学・福祉工学</li>
            </ul>
              <h5>健康・スポーツ科学</h5>
              <ul>
              <li>身体教育学</li>
<li>スポーツ科学</li>
<li>応用健康科学</li>
            </ul>
              <h5>子ども学</h5>
              <ul>
              <li>子ども学(子ども環境学)</li>
            </ul>
              <h5>生体分子科学</h5>
              <ul>
              <li>生物分子化学</li>
<li>ケミカルバイオロジー</li>
            </ul>
              <h5>脳科学</h5>
            <ul>
            <li>基盤・社会脳科学</li>
<li>脳計測科学</li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>人文社会系</h3>
            <h4>総合人文社会</h4>
            <h5>地域研究</h5>
            <ul>
            <li>地域研究</li>
            </ul>
              <h5>ジェンダー</h5>
              <ul>
              <li>ジェンダー</li>
            </ul>
              <h5>観光学</h5>
            <ul>
            <li>観光学</li>
            </ul>
            <h4>人文学</h4>
            <h5>哲学</h5>
            <ul>
            <li>哲学・倫理学</li>
<li>中国哲学・印度哲学・仏教学</li>
<li>宗教学</li>
<li>思想史</li>
            </ul>
              <h5>芸術学</h5>
              <ul>
              <li>美学・芸術諸学</li>
<li>美術史</li>
<li>芸術一般</li>
            </ul>
              <h5>文学</h5>
              <ul>
              <li>日本文学</li>
<li>英米・英語圏文学</li>
<li>ヨーロッパ文学</li>
<li>中国文学</li>
<li>文学一般</li>
            </ul>
              <h5>言語学</h5>
              <ul>
              <li>日本語学</li>
<li>英語学</li>
<li>日本語教育</li>
<li>外国語教育</li>
            </ul>
              <h5>史学</h5>
              <ul>
              <li>史学一般</li>
<li>日本史</li>
<li>アジア史・アフリカ史</li>
<li>ヨーロッパ史・アメリカ史</li>
<li>考古学</li>
            </ul>
              <h5>人文地理学</h5>
              <ul>
              <li>人文地理学</li>
            </ul>
              <h5>文化人類学</h5>
            <ul>
            <li>文化人類学・民俗学</li>
            </ul>
            <h4>社会科学</h4>
            <h5>法学</h5>
            <ul>
            <li>基礎法学</li>
<li>公法学</li>
<li>国際法学</li>
<li>社会法学</li>
<li>刑事法学</li>
<li>民事法学</li>
<li>新領域法学</li>
            </ul>
              <h5>政治学</h5>
              <ul>
              <li>政治学</li>
<li>国際関係論</li>
            </ul>
              <h5>経済学</h5>
              <ul>
              <li>理論経済学</li>
<li>経済学説・経済思想</li>
<li>経済統計</li>
<li>経済政策</li>
<li>財政・公共経済</li>
<li>金融・ファイナンス</li>
<li>経済史</li>
            </ul>
              <h5>経営学</h5>
              <ul>
              <li>経営学</li>
<li>商学</li>
<li>会計学</li>
            </ul>
              <h5>社会学</h5>
              <ul>
              <li>社会学</li>
<li>社会福祉学</li>
            </ul>
              <h5>心理学</h5>
              <ul>
              <li>社会心理学</li>
<li>教育心理学</li>
<li>臨床心理学</li>
<li>実験心理学</li>
            </ul>
              <h5>教育学</h5>
            <ul>
            <li>教育学</li>
<li>教育社会学</li>
<li>教科教育学</li>
<li>特別支援教育</li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>理工系</h3>
            <h4>総合理工</h4>
            <h5>ナノ・マイクロ科学</h5>
            <ul>
            <li>ナノ構造化学</li>
<li>ナノ構造物理</li>
<li>ナノ材料化学</li>
<li>ナノ材料工学</li>
<li>ナノバイオサイエンス</li>
<li>ナノマイクロシステム</li>
            </ul>
              <h5>応用物理学</h5>
              <ul>
              <li>応用物性</li>
<li>結晶工学</li>
<li>薄膜・表面界面物性</li>
<li>光工学・光量子科学</li>
<li>プラズマエレクトロニクス</li>
<li>応用物理学一般</li>
            </ul>
              <h5>量子ビーム科学</h5>
              <ul>
              <li>量子ビーム科学</li>
            </ul>
              <h5>計算科学</h5>
            <ul>
            <li>計算科学</li>
            </ul>
            <h4>数物系科学</h4>
            <h5>数学</h5>
            <ul>
            <li>代数学</li>
<li>幾何学</li>
<li>解析学基礎</li>
<li>数学解析</li>
<li>数学基礎・応用数学</li>
            </ul>
              <h5>天文学</h5>
              <ul>
              <li>天文学</li>
            </ul>
              <h5>物理学</h5>
              <ul>
              <li>物性I</li>
<li>物性II</li>
<li>数理物理・物性基礎</li>
<li>原子・分子・量子エレクトロニクス</li>
<li>生物物理・化学物理・ソフトマターの物理</li>
            </ul>
              <h5>地球惑星科学</h5>
              <ul>
              <li>固体地球惑星物理学</li>
<li>気象・海洋物理・陸水学</li>
<li>超高層物理学</li>
<li>地質学</li>
<li>層位・古生物学</li>
<li>岩石・鉱物・鉱床学</li>
<li>地球宇宙化学</li>
            </ul>
              <h5>プラズマ科学</h5>
            <ul>
            <li>プラズマ科学</li>
            </ul>
            <h4>化学</h4>
            <h5>基礎化学</h5>
            <ul>
            <li>物理化学</li>
<li>有機化学</li>
<li>無機化学</li>
            </ul>
              <h5>複合化学</h5>
              <ul>
              <li>機能物性化学</li>
<li>合成化学</li>
<li>高分子化学</li>
<li>分析化学</li>
<li>生体関連化学</li>
<li>グリーン・環境化学</li>
<li>エネルギー関連化学</li>
            </ul>
              <h5>材料化学</h5>
            <ul>
            <li>有機・ハイブリッド材料</li>
<li>高分子・繊維材料</li>
<li>無機工業材料</li>
<li>デバイス関連化学</li>
            </ul>
            <h4>工学</h4>
            <h5>機械工学</h5>
            <ul>
            <li>機械材料・材料力学</li>
<li>生産工学・加工学</li>
<li>設計工学・機械機能要素・トライボロジー</li>
<li>流体工学</li>
<li>熱工学</li>
<li>機械力学・制御</li>
<li>知能機械学・機械システム</li>
            </ul>
              <h5>電気電子工学</h5>
              <ul>
              <li>電力工学・電力変換・電気機器</li>
<li>電子・電気材料工学</li>
<li>電子デバイス・電子機器</li>
<li>通信・ネットワーク工学</li>
<li>計測工学</li>
<li>制御・システム工学</li>
            </ul>
              <h5>土木工学</h5>
              <ul>
              <li>土木材料・施工・建設マネジメント</li>
<li>構造工学・地震工学・維持管理工学</li>
<li>地盤工学</li>
<li>水工学</li>
<li>土木計画学・交通工学</li>
<li>土木環境システム</li>
            </ul>
              <h5>建築学</h5>
              <ul>
              <li>建築構造・材料</li>
<li>建築環境・設備</li>
<li>都市計画・建築計画</li>
<li>建築史・意匠</li>
            </ul>
              <h5>材料工学</h5>
              <ul>
              <li>金属物性・材料</li>
<li>無機材料・物性</li>
<li>複合材料・表界面工学</li>
<li>構造・機能材料</li>
<li>材料加工・組織制御工学</li>
<li>金属・資源生産工学</li>
            </ul>
              <h5>プロセス・化学工学</h5>
              <ul>
              <li>化工物性・移動操作・単位操作</li>
<li>反応工学・プロセスシステム</li>
<li>触媒・資源化学プロセス</li>
<li>生物機能・バイオプロセス</li>
            </ul>
              <h5>総合工学</h5>
            <ul>
            <li>航空宇宙工学</li>
<li>船舶海洋工学</li>
<li>地球・資源システム工学</li>
<li>核融合学</li>
<li>原子力学</li>
<li>エネルギー学</li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>生物系</h3>
            <h4>総合生物</h4>
            <h5>神経科学</h5>
            <ul>
            <li>神経生理学・神経科学一般</li>
<li>神経解剖学・神経病理学</li>
<li>神経化学・神経薬理学</li>
            </ul>
              <h5>実験動物学</h5>
              <ul>
              <li>実験動物学</li>
            </ul>
              <h5>腫瘍学</h5>
              <ul>
              <li>腫瘍生物学</li>
<li>腫瘍診断学</li>
<li>腫瘍治療学</li>
            </ul>
              <h5>ゲノム科学</h5>
              <ul>
              <li>ゲノム生物学</li>
<li>ゲノム医科学</li>
<li>システムゲノム科学</li>
            </ul>
              <h5>生物資源保全学</h5>
              <ul>
              <li>生物資源保全学</li>
            </ul>
            <h4>生物学</h4>
            <h5>生物科学</h5>
            <ul>
            <li>分子生物学</li>
<li>構造生物化学</li>
<li>機能生物化学</li>
<li>生物物理学</li>
<li>細胞生物学</li>
<li>発生生物学</li>
            </ul>
              <h5>基礎生物学</h5>
              <ul>
              <li>植物分子・生理科学</li>
<li>形態・構造</li>
<li>動物生理・行動</li>
<li>遺伝・染色体動態</li>
<li>進化生物学</li>
<li>生物多様性・分類</li>
<li>生態・環境</li>
            </ul>
              <h5>人類学</h5>
            <ul>
            <li>自然人類学</li>
<li>応用人類学</li>
            </ul>
            <h4>農学</h4>
            <h5>生産環境農学</h5>
            <ul>
            <li>遺伝育種科学</li>
<li>作物生産科学</li>
<li>園芸科学</li>
<li>植物保護科学</li>
            </ul>
              <h5>農芸化学</h5>
              <ul>
              <li>植物栄養学・土壌学</li>
<li>応用微生物学</li>
<li>応用生物化学</li>
<li>生物有機化学</li>
<li>食品科学</li>
            </ul>
              <h5>森林圏科学</h5>
              <ul>
              <li>森林科学</li>
<li>木質科学</li>
            </ul>
              <h5>水圏応用科学</h5>
              <ul>
              <li>水圏生産科学</li>
<li>水圏生命科学</li>
            </ul>
              <h5>社会経済農学</h5>
              <ul>
              <li>経営・経済農学</li>
<li>社会・開発農学</li>
            </ul>
              <h5>農業工学</h5>
              <ul>
              <li>地域環境工学・計画学</li>
<li>農業環境・情報工学</li>
            </ul>
              <h5>動物生命科学</h5>
              <ul>
              <li>動物生産科学</li>
<li>獣医学</li>
<li>統合動物科学</li>
            </ul>
              <h5>境界農学</h5>
            <ul>
            <li>昆虫科学</li>
<li>環境農学(含ランドスケープ科学)</li>
<li>応用分子細胞生物学</li>
            </ul>
            <h4>医歯薬学</h4>
            <h5>薬学</h5>
            <ul>
            <li>化学系薬学</li>
<li>物理系薬学</li>
<li>生物系薬学</li>
<li>薬理系薬学</li>
<li>天然資源系薬学</li>
<li>創薬化学</li>
<li>環境・衛生系薬学</li>
<li>医療系薬学</li>
            </ul>
              <h5>基礎医学</h5>
              <ul>
              <li>解剖学一般(含組織学・発生学)</li>
<li>生理学一般</li>
<li>環境生理学(含体力医学・栄養生理学)</li>
<li>薬理学一般</li>
<li>医化学一般</li>
<li>病態医化学</li>
<li>人類遺伝学</li>
<li>人体病理学</li>
<li>実験病理学</li>
<li>寄生虫学(含衛生動物学)</li>
<li>細菌学(含真菌学)</li>
<li>ウイルス学</li>
<li>免疫学</li>
            </ul>
              <h5>境界医学</h5>
              <ul>
              <li>医療社会学</li>
<li>応用薬理学</li>
<li>病態検査学</li>
<li>疼痛学</li>
<li>医学物理学・放射線技術学</li>
            </ul>
              <h5>社会医学</h5>
              <ul>
              <li>疫学・予防医学</li>
<li>衛生学・公衆衛生学</li>
<li>病院・医療管理学</li>
<li>法医学</li>
            </ul>
              <h5>内科系臨床医学</h5>
              <ul>
              <li>内科学一般(含心身医学)</li>
<li>消化器内科学</li>
<li>循環器内科学</li>
<li>呼吸器内科学</li>
<li>腎臓内科学</li>
<li>神経内科学</li>
<li>代謝学</li>
<li>内分泌学</li>
<li>膠原病・アレルギー内科学</li>
<li>感染症内科学</li>
<li>小児科学</li>
<li>胎児・新生児医学</li>
<li>皮膚科学</li>
<li>精神神経科学</li>
<li>放射線科学</li>
            </ul>
              <h5>外科系臨床医学</h5>
              <ul>
              <li>外科学一般</li>
<li>消化器外科学</li>
<li>心臓血管外科学</li>
<li>呼吸器外科学</li>
<li>脳神経外科学</li>
<li>整形外科学</li>
<li>麻酔科学</li>
<li>泌尿器科学</li>
<li>産婦人科学</li>
<li>耳鼻咽喉科学</li>
<li>眼科学</li>
<li>小児外科学</li>
<li>形成外科学</li>
<li>救急医学</li>
            </ul>
              <h5>歯学</h5>
              <ul>
              <li>形態系基礎歯科学</li>
<li>機能系基礎歯科学</li>
<li>病態科学系歯学・歯科放射線学</li>
<li>保存治療系歯学</li>
<li>補綴・理工系歯学</li>
<li>歯科医用工学・再生歯学</li>
<li>外科系歯学</li>
<li>矯正・小児系歯学</li>
<li>歯周治療系歯学</li>
<li>社会系歯学</li>
            </ul>
              <h5>看護学</h5>
            <ul>
            <li>基礎看護学</li>
<li>臨床看護学</li>
<li>生涯発達看護学</li>
<li>高齢看護学</li>
<li>地域看護学</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- modal dialog END -->
  <script type="text/javascript">
    $(function() {
      $(".trigger").click(function() {
        $("#modalTrigger").trigger('click');
      });
      $("#saimoku li").click(function() {
        var saimoku = $(this).text();
        $('#sentakuShumoku').val(saimoku);
      });
      $("#set").click(function() {
        var shumoku = $('#sentakuShumoku').val();
        $('#shumokubetsu').val(shumoku);
      });
    });
  </script>



<div class="col-md-6">
<?php include("./index_chuushutsujouken.html"); ?>
</div>
</div>


<?php include("./template-footer.php"); ?>
